### ISSUE TITLE
Proposals for v0.1.0

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/OldMeshes.jl#20]
I've been adding a few non-breaking features recently. Once I am finished I think we should tag a new version and work on package uniformity. I think we should bump the minor version and implement these (breaking) changes. I'll add some ideas to this issue as I think of them.

API:
- [x] Uniform API for import/export
- [x] Uniform function naming

Mesh Type:
- [x] Determine and represent if a mesh is [face-vertex](https://en.wikipedia.org/wiki/Polygon_mesh#Face-vertex_meshes). (Implemented with Base.unique)

Extensions:
- [ ] Store vertex normals
- [ ] Store face normals
- [ ] Extensible properties

**Comment by twadleigh** [comment]
- Uniform API for import/export
- Uniform function naming

Yes, please. I started writing Meshes.jl before there had emerged clearer naming conventions. The conventions still aren't that precise. I have since decided to follow Python's PEP8 (which is consistent with, but more specific than, Julia's current best practices) for my code and would recommend we do the same for Meshes.jl.
- Break Mesh type into TopologicalMesh and NonTopologicalMesh

Definitely worth considering a type hierarchy. I have made a few attempts in the past. A "non-topological" mesh strains the meaning of the term, but I would understand that it would be included, given a real need.
- Store vertex normals
- Store face normals

It might be worthwhile considering how to associate arbitrary properties with vertices and faces. (Maybe something like the way that Images.jl does it?)

**Comment by sjkelly** [comment]
> Yes, please. I started writing Meshes.jl before there had emerged clearer naming conventions. The conventions still aren't that precise. I have since decided to follow Python's PEP8 (which is consistent with, but more specific than, Julia's current best practices) for my code and would recommend we do the same for Meshes.jl.

I agree PEP8 is a very good guide. So far I have found the Julia style guide to be the most helpful. 

> Definitely worth considering a type hierarchy. I have made a few attempts in the past. A "non-topological" mesh strains the meaning of the term, but I would understand that it would be included, given a real need.

What we need to descibe is something that is not a true [Face-Vertex](https://en.wikipedia.org/wiki/Polygon_mesh#Face-vertex_meshes) mesh. I agree "non-topological" is the wrong term. Maybe we can eliminate the `has_topology` flag and just make a `isfacevertex` function. If the length of the length of the vertex list is equal to the length of all unique vertices it should be a face-vertex mesh.

> It might be worthwhile considering how to associate arbitrary properties with vertices and faces. (Maybe something like the way that Images.jl does it?)

i am not familiar with the Images.jl implementation details. I will look into it since i'm sure Tim Holy's code will be insightful.

**Comment by sjkelly** [comment]
Updated the OP with your suggestions

**Comment by michelk** [comment]
> It might be worthwhile considering how to associate arbitrary properties with vertices and faces. 

I would appreciate this.

**Comment by sjkelly** [comment]
This is now fixed and the Mesh type is stored in GeometryTypes.
