### ISSUE TITLE
Extending the Mesh-types

### ISSUE THREAD

**Issue by michelk** [JuliaGeometry/OldMeshes.jl#3]
What do you think about extending the types to consider different
mesh-representations?
- IndexedFaceSet
- FaceSet
- HalfEdgeSet

**Comment by twadleigh** [comment]
Maybe we can have an AbstractMesh base type and define a set of methods common to all meshes.

The current Mesh type was chosen because it is a form particularly appropriate for a Mesh when you are "done" with it. Other mesh forms are more appropriate for manipulation (e.g., I use a half-edge representation for mesh simplification).

**Comment by twadleigh** [comment]
I'm guessing that you intend "IndexedFaceSet" to correspond more or less with the existing Mesh type (a shared vertex representation). Is "FaceSet" just a triangle representation without vertex sharing (vertex coords stored with the face)?

**Comment by michelk** [comment]
Exactly. My suggestion would be

```
immutable IndexedFace
    v1 :: Int64
    v2 :: Int64
    v3 :: Int64
end

type IndexedFaceSet
    vertices :: Vector{Vertex}
    faces :: Vector{IndexedFace}
end

type Face
v1 :: Vertex
v2 :: Vertex
v3 :: Vertex
end

typealias FaceSet Vector{Face}
```

**Comment by sjkelly** [comment]
See: https://github.com/JuliaGeometry/GeometryTypes.jl

0.3 compatibility in on the v0.1.x branch.

**Comment by yeesian** [comment]
My comments are vague and broad and I am sorry for being alarmist.

You have been really prompt and polite and comprehensive in handling it. Thank you.
